# Generated by Django 4.0.3 on 2022-03-14 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_lfg', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='r',
            new_name='user',
        ),
    ]
