# Generated by Django 4.0.3 on 2022-03-22 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_lfg', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='twitter_user',
            field=models.CharField(max_length=50),
        ),
    ]
