# Generated by Django 4.0.3 on 2022-04-03 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='twitter_user',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
