# Generated by Django 4.0.3 on 2022-04-03 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_customuser_twitter_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='twitter_user',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
